grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True

    search_param_grid:
      fit_intercept:
      - True


  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
      - 2
      - 4
      - 6
      n_estimators:
      - 10
      - 20

  model_2:
    module: sklearn.tree
    class: DecisionTreeRegressor
    search_param_grid:
      max_depth:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9


  model_3:
    module: sklearn.ensemble
    class: ExtraTreesRegressor
    search_param_grid:
      max_depth:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8


  model_4:
    module: sklearn.ensemble
    class: GradientBoostingRegressor
    search_param_grid:
      max_depth: 
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7    